baseURL = "https://originalmhv.github.io/MHV/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Jane Doe"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[params]
title = "Hello 👋"
author = "Michael H. Valen"
description = "Welcome to my personal portfolio website. Send me a email if you are wondering about something and I'll answer you shortly"
profilePicture = "images/profilePicture.jpg"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Projects"
  weight = 300
  identifier = "projects"
  url = "/projects/"

  [[menu.main]]
  name = "Skills"
  weight = 400
  identifier = "skills"
  url = "/skills/"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/michaelhvalen/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/OriginalMHV"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "Instagram"
url = "https://www.instagram.com/officialmhv/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "michaelhv@uia.no"



